### ISSUE TITLE
Proxy endpoints force chunked transfer-encoding

### ISSUE THREAD

**Issue by rabeyta** [Nike-Inc/riposte#29]
This issue is around the StreamingAsyncHttpClient. When a proxy endpoint is being used, the content-length header is always removed and transfer-encoding of 'chunked' is always added regardless of what the caller passes in.

The scope of this issue is to remove this behavior and enable the client to set whatever headers they want and the proxy endpoints will not modify the request and pass it through to the downstream host unmodified.

**Comment by nicmunroe** [comment]
Good catch. As long as there are solid tests showing that downstream systems receive the payloads correctly from a bytes-on-the-wire perspective in the following three cases I'm ok with (actually really happy about) this change:

1. Incoming request to the proxy/router endpoint has a chunked transfer-encoding.
2. Incoming request is *not* chunked, but has a content-length header instead.
3. Incoming request has not defined either transfer-encoding or content-length.

Chunked incoming requests should stay chunked for the downstream system. Non-chunked incoming requests should stay non-chunked for the downstream system. And payloads should arrive at the downstream system correctly (i.e. identical to the original request payload).

**Comment by nicmunroe** [comment]
Based on issue #32, test case #3 doesn't make sense as it's an invalid HTTP request. So just test cases 1 and 2 (which you've done).

**Comment by nicmunroe** [comment]
Released in version 0.9.1.
