### ISSUE TITLE
AwsUtil hard coded

### ISSUE THREAD

**Issue by 253117966** [Nike-Inc/riposte#35]
AwsUtil has the follow code：
public static final String AMAZON_METADATA_URL_BASE = "http://169.254.169.254";
It seems that AwsUtil should be removed from riposte framework ?

**Comment by nicmunroe** [comment]
See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval. This is following the AWS documentation for retrieving metadata about ec2 instances - it's intentionally hardcoded (as per the AWS docs) and is not unique to a given set of users.

Does that help, or am I misunderstanding your concern?

**Comment by 253117966** [comment]
Thanks! But AwsUtil is a helper class for dealing with AWS related stuff. I think it should not include in riposte-async-http-client module.

**Comment by adriancole** [comment]
It is increasingly common for libraries to have helpers for
platform/environment stuff (ex okhttp has netty things). Provided it
doesn't introduce runtime dependencies, is there a concern besides the
distraction? would the distraction be more limited if the util was in a
"platform" or "internal" package?

**Comment by 253117966** [comment]
Thinks! 
If AMAZON_METADATA_URL_BASE changed for some reason then i could not use AwsUtil? Maybe AMAZON_METADATA_URL_BASE should be configable ^_^

**Comment by adriancole** [comment]
concrete scenarios are generally more actionable than abstract ones.. do you currently have a scenario where you need this changed? If so, for what product? While AWS stands for amazon web services, it definitely works here. If you have a clone of AWS, it might need different changes. Some explanation of what harm is done can help in deciding what to do.

**Comment by 253117966** [comment]
I have not use Riposte in production.
Riposte is a very nice framework for microservice,  i am trying to use it recently and i found the hardcoded url, it is not limited for me to use this framework. 
I think i have no questions now ^_^

Thanks for your answer.

**Comment by nicmunroe** [comment]
Yeah it's extremely unlikely Amazon will ever change that URL, and no extra dependencies are pulled into the module for AwsUtil. It's only there as a convenience if you happen to be deployed in AWS, otherwise you can ignore it.

(Also - thank you for jumping in @adriancole!)
