### ISSUE TITLE
Should i use riposte in production directly?

### ISSUE THREAD

**Issue by vicbell** [Nike-Inc/riposte#36]
Hi, 
1.Can i use riposte in production directly?
2.The "Performance Comparisons" shows that the “CPU Usage” is very high for riposte, our production need the CPU Usage lower than 70% generally，Concurrent Call is more than 100, will it be a problem?

**Comment by nicmunroe** [comment]
Hi @VicBing,

1. Of course you should always do proper testing, but we use Riposte in production and have had good success. 
2. The performance comparisons in the readme are showing *maximum* throughput on a specific machine size for specific use cases. Riposte tends to handle throughput linearly - i.e. double the load, double the CPU. Half the load, half the CPU. So it will entirely depend on what your application is doing and how big the machine is that's running it. We tend to find that Riposte can run an application on smaller machines and/or with lower CPU usage at a given throughput than other frameworks, but of course we can't predict how it will run for you, so again, make sure you do proper load testing.
