### ISSUE TITLE
Remove references to `OneTimeTask`

### ISSUE THREAD

**Issue by nicmunroe** [Nike-Inc/riposte#51]
Netty's `OneTimeTask` is an internal class (it has "internal" in its package name) and is therefore not for public usage. Using this can lock users into very specific versions of Netty - see issue #50 for an example.

Just replace usages of `OneTimeTask` with a lambda.

**Comment by vicbell** [comment]
This bug is fixed in 0.9.4, why not close it ?

**Comment by nicmunroe** [comment]
Because I forgot to close it. :) Thanks for the reminder!
