### ISSUE TITLE
What is the usage of X-B3-TraceId, traceId, parentSpanId and spanId ?

### ISSUE THREAD

**Issue by vicbell** [Nike-Inc/riposte#54]
Ｉ use `whatwg-fetch` to call my endpoint like this:
```javascript
const xB3Traceid = localStore.xB3Traceid; // From the fist call , the server return one and I store it to localStore, here i reuse it.
const requestURL = 'http://XXX';
const headers = {};
if(xB3Traceid) {
  headers['X-B3-TraceId'] = xB3Traceid;
}
fetch(requestURL, { mode: 'cors', headers })
```
I use React as my front, I want to use 'X-B3-TraceId' from the first call  to trace all of the user call log. So I stored  'X-B3-TraceId' after the first call and I send it to the server in the later calls. Am i in the rigth way to use  'X-B3-TraceId' ?

**Here I made three calls and the follow logs confused me：**

**First call** ,'`X-B3-TraceId`' is not set to the request header. `parentSpanId` in the log is null and `traceId` has a value and `spanId` is also has a value  in VALID_WINGTIPS_SPANS logs.After the first call i stored the '`X-B3-TraceId`' for later use.

Here is first call logs:
_2017-05-16T00:45:59,730+08:00 [epollEventLoopGroup-4-6] |-INFO  VALID_WINGTIPS_SPANS appname=datacenter environment=prod version=NA traceId=0b1a74feee1f1365 - [DISTRIBUTED_TRACING] {"`traceId`":"0b1a74feee1f1365","`parentSpanId`":"null","`spanId`":"f26b33a326b86fe3","spanName":"GET_/v1/proxy","sampleable":"true","userId":"null","spanPurpose":"SERVER","startTimeEpochMicros":"1494866759540000","durationNanos":"190234649"}_

**Second call**, I use the traceId value which is response from the First call  as the 'X-B3-TraceId' value of the fetch request header, the VALID_WINGTIPS_SPANS logs:

Here is Second call logs:
_2017-05-16T00:46:43,705+08:00 [epollEventLoopGroup-4-7] |-INFO  VALID_WINGTIPS_SPANS appname=datacenter environment=prod version=NA traceId=0b1a74feee1f1365 - [DISTRIBUTED_TRACING] {"`traceId`":"0b1a74feee1f1365","`parentSpanId`":"5c178fb8fae675c7","`spanId`":"9e0f79d69626a0a1","spanName":"GET_/v1/proxy","sampleable":"true","userId":"null","spanPurpose":"SERVER","startTimeEpochMicros":"1494866803508000","durationNanos":"196741859"}_

Here i can see  `spanId` is has another new value and `parentSpanId` is not null and `parentSpanId` is neither related to the first call, what is the parentSpanId used for ? Where it comes? 

**Third call**, use the `traceId` returned from the Second call(It seems that it always return the same `traceId` if i specify one) and also i can see the `parentSpanId` and `spanId` is change to some different values again. The `parentSpanId`(2f92f19e8932117a) from the third call is not equel with the `spanId`(9e0f79d69626a0a1) from the Second call, they are all a new value but the `traceId` is alway return the same value from the respone header(‘X-B3-TraceId’).

Here is Third call logs:
_2017-05-16T00:47:15,398+08:00 [epollEventLoopGroup-4-8] |-INFO  VALID_WINGTIPS_SPANS appname=datacenter environment=prod version=NA traceId=0b1a74feee1f1365 - [DISTRIBUTED_TRACING] {"`traceId`":"0b1a74feee1f1365","`parentSpanId`":"2f92f19e8932117a","`spanId`":"bc08c3aa0e720573","spanName":"GET_/v1/proxy","sampleable":"true","userId":"null","spanPurpose":"SERVER","startTimeEpochMicros":"1494866835196000","durationNanos":"201917663"}
967"}_

I am confused.
Could you tell me or give me some docs to explain the usage of the `X-B3-TraceId`, `traceId`, `parentSpanId` and `spanId`?

**Comment by adriancole** [comment]
http headers contain only a small amount of data:  IDs and sampling flags
these go synchronously with your application requests, and allow the other
side to continue the trace.

https://github.com/openzipkin/b3-propagation#overall-process

If zipkin is enabled, details including these IDs and other data like
duration send asynchronously to zipkin after a request completes.

you can see a diagram about that here under "Example Flow"
http://zipkin.io/pages/architecture.html

**Comment by vicbell** [comment]
@adriancole Mnay Thanks !

I have the follow questions:
1. ` X-B3-TraceId` is same or different from every call of the same client?
2. `X-B3-SpanId` is not send back to the caller, then how could i set the parent(which show be the `X-B3-SpanId` of the the present call) of the next call?
Here is a response shows the absent of `X-B3-SpanId` in the header：
```java
 -- response --
200 OK
Access-Control-Allow-Origin:  *
Access-Control-Expose-Headers:  X-B3-TraceId,X-B3-ParentSpanId,X-B3-SpanId
Access-Control-Allow-Methods:  POST,PUT,GET,OPTIONS,DELETE
Content-Type:  application/json; charset=UTF-8
X-B3-TraceId:  cc6f2b1d67f5ff15
Connection:  keep-alive
Content-Encoding:  gzip
Transfer-Encoding:  chunked
```

**Comment by adriancole** [comment]
>
>
>    1. X-B3-TraceId is same or different from every call of the same
>    client?
>
> different per overall request. each top-level request into your system has
a different trace id. Each step in that request has a different span id

>
>    1. X-B3-SpanId is not send back to the caller, then how could i set
>    the parent(which show be the X-B3-SpanId of the the present call) of
>    the next call?
>    Here is a response shows the absent of X-B3-SpanId in the header：
>
> I don't quite understand. The parent is only used when creating a span.
The span is created before a request is sent. So, there's no relevance to
response headers in span creation.

**Comment by vicbell** [comment]
Thinks!

**Comment by nicmunroe** [comment]
Sorry for not responding on this - I've been unavailable for several weeks (and will continue to be for a few more) and therefore not able to check in on stuff very often.

@adriancole as always many thanks for jumping in and responding. :)

@vicbell The info @adriancole gave you should hopefully have cleared everything up. You also might want to check out the [Wingtips readme](https://github.com/Nike-Inc/wingtips) - it might clarify some things for you as well.
