### ISSUE TITLE
Accessing pathTemplate value at RequestInfoImpl

### ISSUE THREAD

**Issue by ferhatsb** [Nike-Inc/riposte#55]
Hi,
Having multiple paths for an endpoint, I would like to know which one has matched. 
pathTemplate value is protected at RequestInfoImpl and has no getter defined at interface.

Does it makes sense to add a getter for it ?

**Comment by nicmunroe** [comment]
Hi @ferhatsb - yes it does make sense to add a getter for that to the `RequestInfo` interface. I'll leave this issue open as a reminder to add that getter, or you can submit a pull request.

In the meantime, you can call `ChannelAttributes.getHttpProcessingStateForChannel(ctx).get().getMatchingPathTemplate()` to get that value.

**Comment by nicmunroe** [comment]
@ferhatsb this fix will show up in the next release. Thanks @rabeyta for the PR!

**Comment by rabeyta** [comment]
fixed in 0.10.0
