### ISSUE TITLE
Endpoint ability to require request content be present

### ISSUE THREAD

**Issue by rabeyta** [Nike-Inc/riposte#81]
Currently, if the request content is empty, there is no validation performed on the request content. This leads to endpoints adding additional checks in addition to the JSR303 support already provided to require a body be present. `RequestContentValidationHandler` is where this logic is today.

This issue wants to address the lack of a way for endpoints to require a request body.

Solution could be a new method on the `Endpoint` that allows someone to state the request content is required or not. 

This method can have default behavior that keys off the endpoint's requestContentType() response being not-null && not Void type, we can then assume the endpoint wanted to require content and thus throw a bad request to the client.

**Comment by nicmunroe** [comment]
Sounds like a reasonable solution to me! 

If we put the type checking logic into the default `Endpoint` method definition, then we need to make sure that `ProxyRouterEndpoint` overrides it to return "don't explode on empty payload" by default.

**Comment by nicmunroe** [comment]
This was released on version `0.12.0`, but I forgot to close the ticket. Thanks for the work on this!
